name: GitHub Actions Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # 운영체제: ubuntu 최신 버전 (linux)
    steps:
      - name: Print Hello World
        run: echo "Hello World"

      - name: Write multiple commands
        run: |
          echo "Testing"
          echo "Results"
          pwd
