name: GitHub Actions Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest # 운영체제: ubuntu (linux)
    steps:
      - name: Print Hello World
        run: echo "Hello World"
